<div class="grid-container"> 
    <div class="grid-100 mobile-grid-100 tablet-grid-100"> 
        <div id="main_content" class="clearfix">
            <div class="login-form-label">
                <h1><?= C::getLanguageString('registration') ?></h1>
            </div>
            <div class="login-form-field" id="registration">
                <form method="post" action="<?= C::uri( array('user', 'registration') ) ?>">
                    <p><input type="text" name="name" value="<?= ( isset($this->data['name']) ? $this->data['name'] : '' ) ?>" placeholder="<?= C::getLanguageString('user_name') ?>" /> <span style="color: red;"><?= ( isset($this->error['name']) ? $this->error['name'] : '' ) ?></span></p>
                    <p><input type="text" name="surname" value="<?= ( isset($this->data['surname']) ? $this->data['surname'] : '' ) ?>" placeholder="<?= C::getLanguageString('user_surname') ?>" /> <span style="color: red;"><?= ( isset($this->error['surname']) ? $this->error['surname'] : '' ) ?></span></p>
                    <p><input type="text" name="email" value="<?= ( isset($this->data['email']) ? $this->data['email'] : '' ) ?>" placeholder="<?= C::getLanguageString('user_email') ?>" /> <span style="color: red;"><?= ( isset($this->error['email']) ? $this->error['email'] : '' ) ?></span></p>
                    <p><input type="text" name="login" value="<?= ( isset($this->data['login']) ? $this->data['login'] : '' ) ?>" placeholder="<?= C::getLanguageString('login') ?>" /> <span style="color: red;"><?= ( isset($this->error['login']) ? $this->error['login'] : '' ) ?></span></p>
                    <p><input type="password" name="password" value="" placeholder="<?= C::getLanguageString('password') ?>" /> <span style="color: red;"><?= ( isset($this->error['password']) ? $this->error['password'] : '' ) ?></span></p>
                    <p><input type="password" name="repassword" value="" placeholder="<?= C::getLanguageString('repassword') ?>" /> <span style="color: red;"><?= ( isset($this->error['repassword']) ? $this->error['repassword'] : '' ) ?></span></p>
                    <p><input type="hidden" name="antispam" value="<?= $this->antispam ?>" /></p>
                    <p><input type="submit" value="<?= C::getLanguageString('regist') ?>" /></p>
                </form>
                <p><?= C::getLanguageString('register_must') ?></p>
            </div>
        </div>
    </div>
</div>