<?php if( !empty($this->data) ) : ?>
    <?php foreach($this->data as $value) : ?>
        <div class="donor clearfix">					
            <img alt="<?= $value->name . ' ' . $value->surname ?>" src="/images/cropr_120x120/<?= $value->img; ?>" width="120" height="120">
            <?php if($value->id > 0) : ?>
                <a href="<?= C::uri( array('donors', $value->id) ) ?>" class="title"><?= $value->name . ' ' . $value->surname ?></a>
                <div class="clearfix">
                    <p><?= C::getLanguageString('donors_projects_supported') ?> <span class="bolder"><?= $value->count_pays ?></span>, <?= C::getLanguageString('donors_for_sum') ?> <span class="bolder"><?= ( !empty($value->money_sum) ? $value->money_sum : 0 ) ?> грн.</span></p>
                                            <p><?= C::getLanguageString('donors_last_sum') ?> <?= ( !empty($value->last_pay_sum) ? array_shift( explode(",", $value->last_pay_sum) ) : 0 ) ?> грн. (<?= date( "d.m.Y", strtotime($value->last_pay_date) ) ?>)</p>
                    <p><?= C::getLanguageString('donors_day_reg') ?> <?= date( "d.m.Y", strtotime($value->date_reg) ) ?></p>
                </div>
            <?php else : ?>
                <span class="article_title"><?= $value->name . ' ' . $value->surname ?></span>
                <div class="clearfix">
                    <p><?= C::getLanguageString('donors_last_sum') ?> <?= array_shift( explode(",", $value->last_pay_sum) ) ?> грн. (<?= date( "d.m.Y", strtotime($value->last_pay_date) ) ?>)</p>
                </div>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>