<?php if( !empty($this->data) ) : ?>
    <?php foreach($this->data as $key => $value) : ?>
        <div class="project clearfix">
            <div class="clearfix">
                <span class="article_title"><?= $value->title ?></span>
                <span class="date_publish"><?= C::getLanguageString('date_start') ?> <?= date( "d.m.Y", strtotime($value->date_start) ); ?></span>
            </div>
            <img alt="<?= $value->description ?>" src="/images/cropr_200x150/<?= array_shift( explode(",", $value->images) ) ?>" width="200" height="150">
            <div class="clearfix">
                <?php list($value->text,) = explode("{read_more}", $value->text); ?>
                <p><?= strip_tags($value->text) ?></p>
                <a class="readmore" href="<?= C::uri( array('done', $value->id . '-' . $value->alias) ) ?>"><?= C::getLanguageString('done_show_more') ?></a>
                <p class="voted"><?= C::getLanguageString('projects_show_voted') ?> <b><?= $value->count_vote ?></b></p>	
            </div>
            <div class="clearfix">	
                <span class="budget"><?= C::getLanguageString('donor_now_get') ?> <?= $value->money_need ?> грн.</span>
                <span class="needed_done"><?= C::getLanguageString('projects_show_less') ?> <?= ($value->money_need >= $value->money_now ? $value->money_need - $value->money_now : 0) ?> грн.</span>
                <div class="progress">
                    <div class="bar" style="width:<?= ( ($value->money_now / $value->money_need) * 100 ) ?>%;"></div>
                </div>
            </div>	
        </div>
    <?php endforeach; ?>
<?php endif; ?>