<style>
    .lang-title {
        text-align: center;
        font-size: 16px;
        font-weight: bold;
        background: #FF7F0B;
        color: #fff;
    }
    
    .add-path {
        font-size: 20px;
        color: green;
        cursor: pointer;
        background: #f1f1f1;
        border: 1px solid #000;
        border-radius: 5px;
    }
    
    .add-path:hover {
        background: #ddd;
    }
    
    .delete-path {
        font-size: 20px;
        color: red;
        cursor: pointer;
        background: #f1f1f1;
        border: 1px solid #000;
        border-radius: 5px;
    }
    
    .delete-path:hover {
        background: #ddd;
    }
    
    .lang-pack {
        height: 200px;
        overflow: auto;
    }
    
    .selected {
        background-color: #FF7F0B;
        color: #fff;
    }
    
    .per_data {
        border:1px solid #000;
        padding: 2px;
    }
    
    .per_data:hover {
        background-color: #ccc;
        cursor: pointer;
    }
</style>
<div style="margin:10px auto; width: 60%;">
    <div id="langs">
        <?php foreach($this->langs as $key => $per_lang) : ?>
            <div style="float: <?= ( ($key + 1) == count($this->langs) ? 'right' : 'left') ?>; width: <?= ( 95 / count($this->langs) ) ?>%;">
                <div class="lang-title"><?= $per_lang ?></div>
                <div id="<?= $per_lang ?>" class="lang-pack pack-<?= $per_lang ?>">
                    <?php foreach($this->data as $per_data) : ?>
                            <?php if($per_data->mb_lang == $per_lang) : ?>
                                <div  class="per_data" lang="<?= $per_data->mb_lang ?>" id="<?= $per_data->mb_id ?>">
                                    <span id="mb_data" style="display: none;"><?= json_encode( unserialize($per_data->mb_data) ) ?></span>
                                    <span id="mb_mda_id" style="display: none;"><?= $per_data->mb_mda_id ?></span>
                                    <span id="mb_mdc_id" style="display: none;"><?= $per_data->mb_mdc_id ?></span>
                                    /<span id="mdc_controller"><?= $per_data->mdc_controller ?></span>/<span id="mda_action"><?= $per_data->mda_action ?></span>/<span> - <?= $per_data->mda_name ?></span>
                                </div>
                            <?php endif; ?>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <div style="clear: both"></div>
    <div class="edit-form" style="margin-top: 20px;">
        <p>Контроллер: 
            <select id="controllers-path">
                <?php foreach($this->paths as $key => $per_path) : ?>
                    <option id="<?= ( !empty($per_path->mdc_actions) ? $per_path->mdc_actions : 0 ) ?>" value="<?= $per_path->mdc_id ?>" ><?= $per_path->mdc_controller ?></option>
                <?php endforeach; ?>
            </select>
        </p>
        <p>Экшен (страница): 
            <select id="actions-path">
                <?php if( isset($this->paths[0]) && !empty($this->paths[0]->mdc_actions) ) : ?>
                    <?php $actions = explode(",", $this->paths[0]->mdc_actions); ?>
                    <?php foreach($actions as $per_action) : ?>
                        <?php list($action_id, $action_path) = explode(":", $per_action); ?>
                        <option value="<?= $action_id ?>"><?= $action_path ?></option>
                    <?php endforeach; ?>
                <?php endif; ?>
            </select>
        </p>
        <p>Язык: 
            <select id="lang-paths">
                <?php foreach($this->langs as $key => $path_lang) : ?>
                    <option value="<?= $path_lang?>"><?= $path_lang?></option>
                <?php endforeach; ?>
            </select>
        </p>
        <div id="paths-pack">
            <div id="per-path-pack"><span id="path-number">1</span>. <input id="path-name" placeholder="Название" value=""> <input id="path-url" placeholder="URL" value=""></div>
        </div>
        <p><span title="Добавить путь" class="add-path">&nbsp;+&nbsp;</span></p>
        <p><input rel="/admin/savebreadcrubs/" id="save-path" type="button" value="Сохранить" /></p>
    </div>
    <script type="text/javascript">
        
        var _delete_path_event = function() {
            $(this).parent('#per-path-pack').remove();
            $("span[id='path-number']").each(function(index) {
                $(this).html( (++index) );
            });
        };
        
        var _add_path_event = function() {
            $('#paths-pack').append('<div id="per-path-pack"><span id="path-number">' + ( ( $('#paths-pack div').length * 1 ) + (1 * 1) ) + '</span>. <input id="path-name" placeholder="Название" value=""> <input id="path-url" placeholder="URL" value=""> <span title="Убрать путь" class="delete-path">&nbsp;-&nbsp;</span></div>');
            $('.delete-path').unbind("click");
            $('.delete-path').bind("click", _delete_path_event);
        };
        
        $('.add-path').bind("click", _add_path_event);
        
        var _change_controller_action = function(data) {
            if (typeof data == "string") {
                var _data = data;
            } else {
                var _data = $( $(this).find('option:selected').get(0) ).attr('id');
            }

            if(_data !== '0') {
                var _html = [];
                var _exploded_action = _data.split(',');
                
                for(var _key in  _exploded_action) {
                    var _per_action_data = _exploded_action[_key].split(':');
                    _html.push('<option value="' + _per_action_data[0] + '">' + _per_action_data[1] + '</option>');
                }
                
                $('#actions-path').html( _html.join("\n") );
            } else {
                $('#actions-path').html('');
            }
        };
        
        $('#controllers-path').bind("change", _change_controller_action);
        
        var _clear_form = function() {
            $('#paths-pack').html('<div id="per-path-pack"><span id="path-number">1</span>. <input id="path-name" placeholder="Название" value=""> <input id="path-url" placeholder="URL" value=""></div>');
            $('.delete-path').unbind("click");
            $('.delete-path').bind("click", _delete_path_event);
            $('.add-path').unbind("click");
            $('.add-path').bind("click", _add_path_event);
        };
        
        var _select_path = function() {
            
            if( $(this).hasClass('selected') ) {
                $(this).removeClass('selected');
                $('#save-path').attr('rel', '/admin/savebreadcrubs/');
                $('#save-path').val('Сохранить');
                _clear_form();
            } else {
                $('.per_data').removeClass('selected');
                $('#save-path').attr('rel', '/admin/updatebreadcrubs/');
                $('#save-path').val('Обновить');
                $(this).addClass('selected');
                var _lang = $(this).attr('lang');
                var _data = $(this).find('#mb_data').html();
                var _controller = $(this).find('#mb_mdc_id').html();
                var _action = $(this).find('#mb_mda_id').html();

                $('#lang-paths').val(_lang);
                $('#controllers-path').val(_controller);
                $('#actions-path').html('');
                _change_controller_action( $("#controllers-path option:selected").attr('id') );
                $('#actions-path').val(_action);
                var _extract_data = $.parseJSON(_data);
                var _html = [];
                
                for(var _i in _extract_data) {
                    _html.push('<div id="per-path-pack"><span id="path-number">' + ( (_i * 1) + (1 * 1) ) + '</span>. <input id="path-name" placeholder="Название" value="' + _extract_data[_i].name + '"> <input id="path-url" placeholder="URL" value="' + (_extract_data[_i].url !== undefined ? _extract_data[_i].url : '')  + '"> <span title="Убрать путь" class="delete-path">&nbsp;-&nbsp;</span></div>');
                }
                
                $('#paths-pack').html( _html.join("\n") );
                $('.delete-path').unbind("click");
                $('.delete-path').bind("click", _delete_path_event);
            }
        };
        
        $('.per_data').bind("click", _select_path);
        
        $('#save-path').click(function() {
            var _regexp_name_action = /^[a-zа-я0-9][a-zа-я0-9\-\_\.\,\?\!\s]+$/gi;
            var _regexp_path_action = /^[a-z0-9\/]+$/gi;
            
            if( !_regexp_name_action.test( $( $('#per-path-pack').find('#path-name').get(0) ).val() ) ) {
                alert('Укажите Название хотя бы для первой хлебной крошки');
                return;
            }
            
            if( !_regexp_path_action.test( $( $('#per-path-pack').find('#path-url').get(0) ).val() ) ) {
                alert('Укажите URL хотя бы для первой хлебной крошки');
                return;
            }
            
            if( $(this).attr('rel') == '/admin/savebreadcrubs/') {
                var _data_path = [];
                
                $('#paths-pack').find('#per-path-pack*').each(function(){
                    _data_path.push({
                        name : $( $(this).find('#path-name').get(0) ).val(),
                        url : $( $(this).find('#path-url').get(0) ).val()
                    });
                });
                
                $.post(
                    '/admin/savebreadcrubs/', 
                    {
                        mb_mdc_id : $('#controllers-path').val(),
                        mb_mda_id : $('#actions-path').val(),
                        mb_lang : $('#lang-paths').val(),
                        mb_data : _data_path
                    }, 
                    function(data) {
                        if(data == '0') {
                            alert('Данная комбинация хлебных крошек уже присутствует');
                        } else {
                            $( '.pack-' + $('#lang-paths').val() ).append('<div  class="per_data" lang="' + $('#lang-paths').val() + '" id="' + data + '">\
                                <span id="mb_data" style="display: none;">' + JSON.stringify(_data_path) + '</span>\
                                <span id="mb_mda_id" style="display: none;">' + $('#actions-path').val() + '</span>\
                                <span id="mb_mdc_id" style="display: none;">' + $('#controllers-path').val() + '</span>\
                                /<span id="mdc_controller">' + $('#controllers-path option:selected').html() + '</span>/<span id="mda_action">' + $('#actions-path option:selected').html() + '</span>/<span></span>\
                            </div>');
    
                            $('.per_data').unbind("click");
                            $('.per_data').bind("click", _select_path);
                            _clear_form();
                            alert('Успешно Сохранено');
                        }
                    }
                );
            } else {
                var _data_path = [];
                
                $('#paths-pack').find('#per-path-pack*').each(function(){
                    _data_path.push({
                        name : $( $(this).find('#path-name').get(0) ).val(),
                        url : $( $(this).find('#path-url').get(0) ).val()
                    });
                });
                
                $.post(
                    '/admin/updatebreadcrubs/', 
                    {
                        mb_id : $('.per_data.selected').attr('id'),
                        mb_mdc_id : $('#controllers-path').val(),
                        mb_mda_id : $('#actions-path').val(),
                        mb_lang : $('#lang-paths').val(),
                        mb_data : _data_path
                    }, 
                    function(data) {
                        if(data == '0') {
                            alert('Ошибка обновления хлебных крошек');
                        } else {
                            if( $('.per_data.selected').attr('lang') !== $('#lang-paths').val() ) {
                                $( '.pack-' + $('#lang-paths').val() ).append('<div  class="per_data" lang="' + $('#lang-paths').val() + '" id="' + $('.per_data.selected').attr('id') + '">\
                                    <span id="mb_data" style="display: none;">' + JSON.stringify(_data_path) + '</span>\
                                    <span id="mb_mda_id" style="display: none;">' + $('#actions-path').val() + '</span>\
                                    <span id="mb_mdc_id" style="display: none;">' + $('#controllers-path').val() + '</span>\
                                    /<span id="mdc_controller">' + $('#controllers-path option:selected').html() + '</span>/<span id="mda_action">' + $('#actions-path option:selected').html() + '</span>/<span></span>\
                                </div>');
                                $('.per_data.selected').remove();
                            } else {
                                $( $('.per_data.selected').find('#mb_data').get(0) ).html( JSON.stringify(_data_path) );
                                $( $('.per_data.selected').find('#mb_mda_id').get(0) ).html( $('#actions-path').val() );
                                $( $('.per_data.selected').find('#mb_mdc_id').get(0) ).html( $('#controllers-path').val() );
                                $( $('.per_data.selected').find('#mdc_controller').get(0) ).html( $('#controllers-path option:selected').html() );
                                $( $('.per_data.selected').find('#mda_action').get(0) ).html( $('#actions-path option:selected').html() );
                            }
                            
                            $('.per_data').unbind("click");
                            $('.per_data').bind("click", _select_path);
                            _clear_form();
                            alert('Успешно ОБНОВЛЕНО');
                        }
                    }
                );
            }
            
        });
    </script>
</div>