<?php 
    $all_images = explode(",", $this->data['images']);
    $img = array_shift($all_images);
?>
<div class="grid-container"> 
	<div class="grid-100 mobile-grid-100 tablet-grid-100"> 
		<div id="main_content" class="clearfix">
			<div id="project_details">
				<h1><?= $this->data['pl_title'] ?></h1>
				<div class="clearfix">
                                    <div id="gallery">
                                        <a href="/images/<?= $img ?>"><img class="project_image" alt="<?= $this->data['pl_title'] ?>" width="320" height="240" src="/images/cropr_320x240/<?= $img ?>" /></a>
                                        <?php if( !empty($all_images) ) : ?>
                                            <?php foreach($all_images as $per_image) : ?>
                                                <a style="display:none;" href="/images/<?= $per_image ?>"><img alt="<?= $this->data['pl_title'] ?>" width="320" height="240" src="/images/cropr_320x240/<?= $per_image ?>" /></a>
                                            <?php endforeach; ?>
                                            <script type="text/javascript">
                                                $(document).ready(function() {
                                                    $('#gallery a').lightBox();
                                                });
                                            </script>
                                        <?php endif; ?>
                                    </div>
                                    <?php 
                                        $pre_text = $main_text = '';

                                        if( strpos($this->data['pl_text'], '{read_more}') > 0 ) {
                                            list($pre_text, $main_text) = explode("{read_more}", $this->data['pl_text']);
                                        } else {
                                            $pre_text = $this->data['pl_text'];
                                        }
                                    ?>
                                    <?= $pre_text ?>
                                    <?php if( !empty($main_text) ) : ?>
                                        <div class="maintext close" style="display:none;"><?= $main_text ?></div>
                                        <div style="height: 40px; padding: 10px;">
                                            <a class="details" href="javascript:void(0);"><?= C::getLanguageString('project_deteils') ?></a>
                                            <script type="text/javascript">
                                                $(document).ready(function() {
                                                    $('#gallery a').lightBox();
                                                    $('.details').click(function(){
                                                        $('.maintext').toggle(1, function() {
                                                            if( $('.maintext').hasClass('close') ) {
                                                                $('.maintext').removeClass('close');
                                                                $('.maintext').addClass('open');
                                                                $('.details').html('<?= C::getLanguageString('project_close_deteils') ?>');
                                                            } else {
                                                                $('.maintext').removeClass('open');
                                                                $('.maintext').addClass('close');
                                                                $('.details').html('<?= C::getLanguageString('project_deteils') ?>');
                                                            }
                                                        });
                                                    });
                                                });
                                            </script>
                                        </div>
                                    <?php endif; ?>
				</div>
				<div id="progress_form" class="grid-100 mobile-grid-100 tablet-grid-100 clearfix">	
					<div class="grid-70 mobile-grid-100 tablet-grid-70"> 
						<span class="budget"><?= C::getLanguageString('projects_show_need') ?> <?= $this->data['p_need'] ?> грн.</span>
                        <span class="needed"><?= C::getLanguageString('projects_show_less') ?> <?= ($this->data['p_need'] - $this->data['p_current']) ?> грн.</span>
						<div class="progress">
                            <div class="bar" style="width:<?= ( ($this->data['p_current'] / $this->data['p_need']) * 100 ) ?>%;"></div>
                        </div>
					</div>
					<div class="grid-30 mobile-grid-100 tablet-grid-30"> 
						<a class="pay_button" id="support_project" href="javascript:void(0);"><?= C::getLanguageString('projects_show_support') ?></a>
                        <span class="already_done"><?= C::getLanguageString('project_current_money') ?><br> <b><?= $this->data['p_current'] ?> грн.</b></span> 
					</div>
				</div>
                <div id="progress_form" style="display:none;" class="close support_form grid-100 mobile-grid-100 tablet-grid-100 clearfix">
                    <div class="form-pay" style="margin-top: 25px;">
                        <p style="text-align: center; font-size: 26px; line-height: 70px;">
                            <?= C::getLanguageString('create_sum') ?>
                            <input style="font-size: 26px; width: 182px;" value="" placeholder="<?= C::getLanguageString('input_sum') ?>" id="pay-form-sum" />
                            <a style="float: none; position: relative;top: -5px;" class="pay_button get_sum_button" href="javascript:void(0);"><?= C::getLanguageString('create') ?></a>
                        </p>
                    </div>
                    <div class="created_form" style="text-align: center;">
                        
                    </div>
                    <script type="text/javascript">
                        $(document).ready(function() {
                            $('#support_project').click(function() {
                                $('.support_form').toggle(1, function() {
                                    if( $('.support_form').hasClass('close') ) {
                                        $('.support_form').removeClass('close');
                                        $('.support_form').addClass('open');
                                        $('#support_project').html('<?= C::getLanguageString('close') ?>');
                                    } else {
                                        $('.support_form').removeClass('open');
                                        $('.support_form').addClass('close');
                                        $('.form-pay').show();
                                        $('.created_form').html('');
                                        document.getElementById('pay-form-sum').value = '';
                                        $('#support_project').html('<?= C::getLanguageString('projects_show_support') ?>');
                                    }
                                });
                            });
                            
                            $('.get_sum_button').click(function() {
                                var reg = /^[0-9]+([\.][\d]{1,2})?$/ig;
                                
                                if( reg.test( document.getElementById('pay-form-sum').value ) && (document.getElementById('pay-form-sum').value * 1) >= 0.02 ) {
                                    $('.form-pay').hide();
                                    $('.created_form').html('<p align="center" style="font-size: 26px; line-height: 70px;"><?= C::getLanguageString('loading') ?>...</p>');
                                    $('.created_form').load('/<?= C::$lang?>/projects/createpay/<?= $this->data['p_id'] ?>/' + document.getElementById('pay-form-sum').value + '/');
                                } else {
                                    alert('<?= C::getLanguageString('only_nmeric') ?>');
                                }
                            })
                        });
                    </script>
                </div>
                <p class="voted">
                    <?= C::getLanguageString('vote_text') ?> 
                    <b><?= $this->data['p_count_vote'] ?></b> 
                    <?php if( Fw_Auth::isValid() ) : ?>
                        <?php if( is_numeric($this->data['pv_id']) ) : ?>
                            <a class="vote_project already_voted" href="javascript:void(0);"><?= C::getLanguageString('vote_allready') ?></a>
                            <style>
                                .already_voted {
                                    color: #0057AD !important;
                                    outline: none;
                                    text-decoration: none;
                                    cursor: default;
                                }
                            </style>
                        <?php else : ?>
                            <a class="vote_project vote-now" href="javascript:void(0);"><?= C::getLanguageString('vote') ?></a>
                            <script type="text/javascript">
                                $(document).ready(function() {
                                    $('.vote-now').click(function(){
                                        $.get('/<?= C::$lang ?>/projects/vote/<?= $this->data['p_id'] ?>', function(data) {
                                                $('.vote-now').html('<?= C::getLanguageString('vote_allready') ?>');
                                                $('.vote_project').removeClass('vote-now');
                                                $('.voted > b').html( ( $('.voted > b').html() * 1 ) + (data * 1) );
                                        });
                                    });
                                })
                            </script>
                        <?php endif; ?>
                    <?php else : ?>
                        <a class="vote_project" href="#dialog"><?= C::getLanguageString('vote') ?></a>
                        <script type="text/javascript">
                            $(document).ready(function() {
                                $('a.vote_project').click(function(e) {
                                        e.preventDefault();
                                        var id = $(this).attr('href');
                                        var maskHeight = $(document).height();
                                        var maskWidth = $(window).width();
                                        $('#mask').css( {width : maskWidth, height : maskHeight} );
                                        $('#mask').fadeIn(200);
                                        var winH = $(window).height();
                                        var winW = $(window).width();
                                        $(id).css('top',  winH/2-$(id).height()/2);
                                        $(id).css('left', winW/2-$(id).width()/2);
                                        $(id).fadeIn(200);
                                });
                                
                                $('.window .close-modal').click(function (e) {
                                        e.preventDefault();
                                        $('#mask, .window').hide();
                                });
                                
                                $('#mask').click(function () {
                                        $(this).hide();
                                        $('.window').hide();
                                });
                        });
                        </script>
                        <style>
                            #mask {
                                position:absolute;
                                left:0;
                                top:0;
                                z-index:9000;
                                background-color:#000;
                                display:none;
                                font-family: Georgia;
                                opacity: 0.7;
                            }
                            #boxes .window {
                                position:absolute;
                                left:0;
                                top:0;
                                width:440px;
                                height:200px;
                                display:none;
                                z-index:9999;
                                padding:20px;
                                text-align: center;
                                font-size: 25px;
                            }
                            #boxes #dialog {
                                width:375px;
                                height:203px;
                                padding:10px;
                                background: #DCDEDD url('/img/back_articles_block.png') center ;
                                border-radius: 5px;
                                -moz-border-radius: 5px;
                            }
                            .close-modal {
                                float: right;
                                margin-top: 74px;
                                font-size: 14px;
                                text-decoration: none;
                            }
                        </style>
                        <div id="boxes">
                                <div id="dialog" class="window">
                                    <?= C::getLanguageString('projects_vote_no') ?> 
                                    <a class="vote-a-con" href="/<?= C::$lang ?>/user/registration/"><?= C::getLanguageString('projects_vote_no_regist') ?></a> 
                                    <?= C::getLanguageString('projects_vote_no_or') ?> 
                                    <a class="vote-a-con" href="/<?= C::$lang ?>/user/login/"><?= C::getLanguageString('projects_vote_no_login') ?></a> 
                                    <?= C::getLanguageString('projects_vote_no_onsite') ?>
                                    <span><a href="#" class="close-modal"/>Закрыть</a>
                                </div>
                                <div id="mask"></div>
                        </div>
                    <?php endif; ?>
                </p>
                <p>
                    <script type="text/javascript" src="//yandex.st/share/share.js" charset="utf-8"></script>
                    <div 
                        data-yashareDescription="<?= $this->data['pl_description'] ?>" 
                        class="yashare-auto-init" 
                        data-yashareImage="<?= C::site_host . '/images/cropr_320x240/' . $img ?>"
                        data-yashareL10n="ru" 
                        cdata-yashareQuickServices="yaru,vkontakte,facebook,twitter,odnoklassniki,moimir" 
                        data-yashareTheme="counter"
                    ></div>
                </p>	
                <hr/>
                <?php if( !empty($this->donors_data) ) : ?>
                    <h2><?= C::getLanguageString('donors_by_project') ?></h2>
                    <div id="donors-data">
                        <?php foreach($this->donors_data as $value) : ?>
                            <div class="donor clearfix">					
                                    <img alt="<?= $value->u_surname . ' ' . $value->u_name ?>" src="/images/cropr_120x120/<?= $value->u_img; ?>" width="120" height="120">
                                    <?php if($value->pp_u_id > 0) : ?>
                                        <a href="<?= C::uri( array('donors', $value->pp_u_id) ) ?>" class="title"><?= $value->u_surname . ' ' . $value->u_name ?></a>
                                    <?php else : ?>
                                        <span class="article_title"><?= $value->u_surname . ' ' . $value->u_name ?></span> 
                                    <?php endif; ?>
                                    <div class="clearfix">
                                    <p><?= C::getLanguageString('project_pay_sum') ?> <?= $value->pp_sum ?> грн.</p>
                                    <p><?= C::getLanguageString('project_day_pay') ?> <?= date( "d.m.Y", strtotime($value->pp_data) ) ?></p>
                                    </div>
                            </div>
                        <?php endforeach ; ?>
                    </div>
                    <div id="pagination">
                            <a class="load-more-donors" href="javascript:void(0);"><?= C::getLanguageString('projects_show_more') ?></a>
                    </div>
                    <script type="text/javascript">
                        $('.load-more-donors').click(function() {
                            $.get('<?= '/' . C::$lang ?>/projects/donors/' + '<?= $this->data['p_id'] ?>/' +  $('#donors-data > .donor').length + '/', function(data) {
                                $("#donors-data").append(data);
                            });
                        });
                    </script>
                <?php endif; ?>
			</div>
		</div>
	</div>
</div>